<?php /** @var \Snowdog\SitemapReader\Controller\SitemapAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sitemap - Importation</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">

    <?php if (isset($_SESSION['flash'])): ?>
        <p class="bg-info"><?= $_SESSION['flash'] ?></p>
        <?php unset($_SESSION['flash']) ?>
    <?php endif ?>

    <div>
        <div class="padded">
            <form class="form-inline" method="post" action="/sitemap">
                <div class="form-group">
                    <label for="sitemap">Sitemap URL</label>
                    <input type="text" name="sitemap" class="form-control" id="sitemap"
                           placeholder="https://example.com/sitemap.xml">
                </div>
                <button type="submit" class="btn btn-primary">Import Sitemap</button>
            </form>
        </div>
    </div>

</div><!-- /.container -->

</body>
</html>